### PR TITLE
Fixes #23

### LINKED ISSUE #23: HTML parsing fails randomly on iOS UIWebView
When running our site in a iOS UIWebView, it happens pretty often that html parsing throws a `null is not an object (evaluating doc.body.firstChild)` exception.

I have unfortunately been unable to create a self-contained example to reproduce it, but it's an issue affecting our users (caught by TrackJS) and that I could reproduce quite consistently in our environment.

I debugged this further and here's what I found: at times (quite rarely, but prominent when using set-dom a lot), `DOMParser.parseFromString` will return a document, but `doc.body` is not available until the next tick, even for a simple markup (like `<div></div>`).

I tried the following:
- parse again when `doc.body` is not available. Does not fix
- recreate a new `parser = DOMParser()` and reparse when `doc.body` is not available. Does not fix
- add some random html at the end of the markup (in case it's some caching optimization). Does not fix

The only solution I found is to call the fallback function (innerHTML-based), only when doc.body is null, since we can't detect this consistently prior to setting up the parseHTML function

I will open a PR shortly. I'd understand if you'd rather not merge this since it's quite a major change on parse-html and it fixes a hard-to-isolate bug, but did not want to not contribute back again :)

### PR DESCRIPTION
**Pull request by max-mathieu**
Cf. bug description, investigation results and context in #23

### CODE REVIEW

**Comment by max-mathieu** [comment]
Let me add a test

**Comment by max-mathieu** [comment]
@DylanPiercey I am not sure what you would prefer there. I tried adding (some crazy) tests to mock all the various browsers limitations, but the one for IE9 actually doubles the html content and the test fails. Should we just put the while parse-html in istanbul ignore?

Btw, I am not sure I understand the `while(mockBody.firstChild)` line. Doesn't this deplete the mockBody, meaning we can only call this once on <html>, since mockBody is global? (it's very early here, so I may be missing something)

**Comment by max-mathieu** [comment]
I actually found a way to make the test work. I'll reopen later. Still willing to discuss if we just want to ignore that file for coverage, since it's technically a polyfill

**Comment by max-mathieu** [comment]
I was able to add full unit tests to the parse-html polyfill. It's probably one of the weirdest test files I've ever had to write ;)

Let me know what you think

**Comment by DylanPiercey** [comment]
Thanks for the awesome PR. It looks good to me. I don't have the bandwidth at the moment to give a proper review but at the very least I'd like to get this patch out there.

**Pull request merged**
