### PR TITLE
Updated value property whenever value attribute is changing for element.

### PR DESCRIPTION
**Pull request by durgesh-priyaranjan**
Currently on updating the value, just attribute of the element gets updated. It should also update value property.

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Could you explain what you are trying to achieve here? Parent is the DOM element that has the attributes. Basically it looks like you are saying any time an attribute gets updated, update the 'value' property of the parent which we don't want to do.

**Comment by durgesh-priyaranjan** [comment]
Lets say, I have an element as:
`
<input name="firstName" value="John"/>
`

Now, I am patching it with
`
<input name="firstName" value=""/>
`

set-dom will just change value attribute to ""(empty string), and that change will not reflect shown in UI as 'value' property is still "John".

Let me know if there is any issue in my implementation or understanding.

> any time an attribute gets updated, update the 'value' property of the parent which we don't want to do.

Please let me know, so that I can understand this better.

**Comment by DylanPiercey** [comment]
I was thinking this was what you are trying to do.

Ultimately set-dom was purposefully setup this way since the whole point of it is to maintain state between diffs.

What you are looking for is a controlled input and I have personally found the best way to work with those is manually updating the value with javascript since controlled inputs cannot be fully isomorphic.

Does that make sense?

**Comment by durgesh-priyaranjan** [comment]
Makes sense for universal rendering.

**Comment by DylanPiercey** [comment]
@durgesh-priyaranjan cool, if you need any help figuring out the best way to do something feel free to shoot me a message in the gitter. https://gitter.im/DylanPiercey/set-dom

**Pull request closed without merging**
