### PR TITLE
Fix typo in readme ☺️

### PR DESCRIPTION
**Pull request by maziey93**
Fix typo in readme where `ala` was used instead of `aka` to reference jQuery

### CODE REVIEW

**Comment by DylanPiercey** [comment]
@maziey93 awesome thanks!

**Comment by DylanPiercey** [comment]
Released in 7.4.4 😄

**Comment by maziey93** [comment]
@DylanPiercey lol, your welcome... and by the way great job on rill

**Comment by DylanPiercey** [comment]
Glad to hear you like it! If you ever need any help with it or have any suggestions please don't hesitate to message me 😄.

**Pull request merged**
